POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Another test case",
    "important": false
}

###

GET http://localhost:3001/api/notes/

###

DELETE http://localhost:3001/api/notes/689bc8691f7f8559036ae915

###

PUT http://localhost:3001/api/notes/4
Content-Type: application/json

{
    "important": false
}