POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Another test case",
    "important": false
}

###

GET http://localhost:3001/api/notes/

###

DELETE http://localhost:3001/api/notes/689b5bdea5af8bd584ad8b41

###

PUT http://localhost:3001/api/notes/4
Content-Type: application/json

{
    "important": false
}